

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBox;
            }
        }
    }
}

namespace WebSocketClientCPP
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ LED0Button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IPAddressText;
        private: ::Windows::UI::Xaml::Controls::TextBox^ PortNoText;
        private: ::Windows::UI::Xaml::Controls::Button^ ConnectButton;
        private: ::Windows::UI::Xaml::Controls::Button^ RefreshButton;
        private: ::Windows::UI::Xaml::Controls::Button^ LED4Button;
        private: ::Windows::UI::Xaml::Controls::Button^ LED1Button;
        private: ::Windows::UI::Xaml::Controls::Button^ LED5Button;
        private: ::Windows::UI::Xaml::Controls::Button^ LED2Button;
        private: ::Windows::UI::Xaml::Controls::Button^ LED6Button;
        private: ::Windows::UI::Xaml::Controls::Button^ LED3Button;
        private: ::Windows::UI::Xaml::Controls::Button^ LED7Button;
    };
}

